### ISSUE TITLE
Comparison table to readme

### ISSUE THREAD

**Issue by JuhQ** [imkimchi/ni#1]
I think it would add great deal of value if this project would have comparison table of how it compares to npm, yarn and other tools

**Comment by bakerej** [comment]
Could not agree more. I enjoy yarn and I'm glad I made the switch -- what does ni have to offer? Just its improvements over npm would be insufficient.

**Comment by imkimchi** [comment]
It's not a whole another package like yarn. It just works the same as npm install, but better than original.

**Comment by JuhQ** [comment]
Better how?
Comparison table would tell everyone how it's better :)

**Comment by imkimchi** [comment]
@JuhQ Take a look :) https://github.com/imkimchi/ni#why

**Comment by JuhQ** [comment]
You know, I did read that before creating this issue.

**Comment by imkimchi** [comment]
can you explain briefly what the "comparison table" should show?
It's basically built on npm, which means It'd just work the same as npm does. nothing special.
