### ISSUE TITLE
Not compatible on Windows

### ISSUE THREAD

**Issue by Armaldio** [imkimchi/ni#3]
At least W10

--> https://technet.microsoft.com/en-us/library/ee176914.aspx

There is a New-Item command. And the alias for this command is ni

**Comment by imkimchi** [comment]
Oh, I never thought about windows. you would need to change New-item's alias to something like `newi` and reinstall or if you don't want to change the New-item's alias,  change `npm-better-install`'s,  by using DOSKEY command.

```
doskey macroName=macroDefinition
```

**Comment by Armaldio** [comment]
Yeah, I was surprised too
Will try what you suggest

**Comment by imkimchi** [comment]
Try it out and let me know :)
