### ISSUE TITLE
Installed package count is not correct

### ISSUE THREAD

**Issue by ayhansipahi** [imkimchi/ni#6]
https://asciinema.org/a/WdYbtn6UeyeYLsM3o7IA9d5Ed

in my record you will see it saying it installed 8 packages

but installing more packages. 

I have 20 packages total. 

ni added 2 updated 10 packages.

and its not installing dev dependicies.

**Comment by imkimchi** [comment]
It actually only shows the count of installed missing dependencies not all packages.
and It currently doesn't install dev dependencies because this project was meant to install missing dependencies, but if you want the feature to be included in this module, always feel free to send PR!
